<?php
/**	op-unit-form:/template/display.phtml
 *
 * @created    2024-06-13
 * @package    op-unit-form
 * @copyright  2024 Tomoaki Nagahara All Rights Reserved.
 */

/**	Declare strict type
 *
 */
declare(strict_types=1);

/**	Namespace
 *
 */
namespace OP\UNIT\FORM;

/* @var $form \OP\UNIT\Form */

?>
<?php $form->Start() ?>
<table>
	<?php foreach( $form->Config()['input'] ?? [] as $name => $value ): ?>
	<tr>
		<th><?php $form->Label($name) ?></th>
		<td><?php $form->Input($name) ?></td>
	</tr>
	<tr>
		<td></td>
		<td><?php $form->Error($name) ?></td>
	</tr>
	<?php endforeach; ?>
	<tr>
		<td></td>
		<td><button> Submit </button></td>
	</tr>
</table>
<?php $form->Finish() ?>
<?php
unset($name, $value);
